### ISSUE TITLE
LevelDB - Google Key-Value store library

### ISSUE THREAD

**Issue by solvingj** [conan-io/wishlist#107] opened 2018-01-18 21:13 UTC
https://github.com/google/leveldb

This is a requirement for cpp-etherium client.  Currently, has a problem in that the windows builds are not fully supported: 

https://github.com/google/leveldb/pull/526

**Comment by Croydon** [comment] 2018-01-21 14:45
Duplicate of #25

**Closed** 2018-01-21 15:10 UTC
