### ISSUE TITLE
g3log

### ISSUE THREAD

**Issue by Brunni** [conan-io/wishlist#62] opened 2017-03-08 21:05 UTC
Hi,

I just started with conan and all this cpp cmake stuff.
So this is my first try:
https://github.com/Brunni/conan-g3log

It is working on Windows Visual Studio build with shared=True and shared=False option.

I tried to get it working on Linux. The build works, but test_package fails with a linker error (both shared and static).

Can someone help me with this?
And one more question: Is the test_package folder also uploaded to conan.io? Do I need to define export_sources?

**Comment by memsharded** [comment] 2017-03-08 22:29
Hi Michael,
I will have a look

No, the test_package folder is not uploaded. ``exports`` and ``exports_sources`` are only if you want to embed other files (as source code files) into the recipe, as an alternative to the ``source()`` method. It would be kind of snapshoting, and can be a good approach if the package recipe is located into the source repo (as otherwise it would be weird to be fetching or cloning your own repo, doable, but weird).
If you want, you can upload it, using ``exports_sources`` but totally unnecessary.

You have put the "unlicensed" license. Please note that the terms of conan.io are that uploads should be free software. Could be even closed source, but the packages are public and for free use, according to some licensing terms. Of course you can use any license if you use your own conan_server.

**Comment by Brunni** [comment] 2017-03-08 22:43
So this means, if you do a conan install --build=missing it will be built but the test_package is not executed? This seems strange to me :)

I just used the license from the original github repo. This seems to be a free to use license: https://github.com/KjellKod/g3log/blob/master/LICENSE

**Comment by memsharded** [comment] 2017-03-08 22:43
You don't need to specify the option in the test package, and then make it transitive, you can just set it directly as:
```bash
$ conan install ... -o g3log:shared=False
```

**Comment by Brunni** [comment] 2017-03-08 22:45
Hi. I just thought, that the test_package should use the same shared flag as the install is using. Otherwise it could happen that it tests the wrong package?

**Comment by memsharded** [comment] 2017-03-08 22:50
Not necessarily, the consumer is just specified the library by name "g3log", and the linker infers what to do. You can simplify and remove it. Will submit a PR with fixes in a couple of minutes.

**Comment by Brunni** [comment] 2017-03-09 21:54
Thank you for your help.
I uploaded one linux package. But I tried this build.py file with use_docker=True but I get this error:
cc1plus: error: unrecognized command line option '-std=c++11'

Do you know what this means?

**Comment by memsharded** [comment] 2017-03-09 23:40
I need more information. When submitting issues, you should:
- Paste a link to the travis build that generates the error. If you are running locally, copy and paste the full trace, or at least a big part of it.
- Clearly indicate the settings you are running with. The OS, the compiler, the compiler version, etc. Check the ``conaninfo.txt`` file.
- When something doesn't work, it is necessary to specify with details what would be the expected result, which is the current result, and steps to reproduce.

Please tell me and we will see what could be. Thanks very much for your feedback.

**Comment by Brunni** [comment] 2017-03-14 22:24
Hi memsharded, sorry for my stupid comment above. I was just a bit stressed.

I still don't understand how the test_package project works.

I can't execute `conan test_package -o shared=True` if I don't have this option in the test_package/conanfile.py defined. But I would like to test the different kinds of builds and linkers here.

So what I'm currently doing is changing a line in test_package.

**Comment by memsharded** [comment] 2017-03-14 23:48
No worries!

- The option "shared" is defining the type of the library being compiled. If a package "g3log" define such option, if it is set to True, it will generate some "g3log.so" or "g3log.dll" (win), and if it is False, the package will contain some "g3log.a" or "g3log.lib" (win)

- Any consumer project, when using the "g3log" package can opt for one type of library or the other: "I want to link with g3log static library" or "I want to link with g3log shared library". So what they do is they specify that they want such package:

```bash
conan install -o g3log:shared=True
```

- The "test_package" subproject, is not building a library, just an executable. It doesn't need to specify if itself is shared or static, because an executable can't be shared or static. This is why the ``test_package/conanfile.py`` doesn't have such ``shared`` option.

- ``$conan test_package`` is just a convenience command that basically does an export + install + build test + run test. The command line arguments provided to it are just arguments for the underlying ``conan install``. So:

```bash
conan test_package -o g3log:shared=True
```
means: I want to install the g3log shared library, and my test_package project will link with it.

Build system and linker will figure out how to link with the library, you don't need to change anything in your consumer ``test_package`` project to link with the shared or static versions of the package.

Please tell me if this makes sense or you have any further question. Cheers!

**Comment by Croydon** [comment] 2020-04-28 11:22
Fixed by https://github.com/conan-io/conan-center-index/pull/1294

**Closed** 2020-04-28 11:55 UTC
