### ISSUE TITLE
SQLPP Connectors - odbc, postgres, mysql, stl, sqlite3

### ISSUE THREAD

**Issue by solvingj** [conan-io/wishlist#112] opened 2018-01-19 17:07 UTC
from bincrafters trello.

**Comment by Croydon** [comment] 2018-01-21 14:51
Is this a duplicate of #8 ?

**Comment by solvingj** [comment] 2018-01-21 15:12
Possibly, I was transferring these items from trello before closing the board so that we didn't lose requests.  Actually, i think it probably warrants a separate ticket for each connector once a solid SQLPP11 package is established.  It seems that in #8, it may not be there yet.

**Comment by Croydon** [comment] 2020-10-20 21:35
We have now sqlpp11 and sqlpp11-connector-sqlite3 in CCI.

I suggest to close this issue and open individual issues in CCI for the connectors desired. Atomic issues are much better

**Closed** 2020-10-21 01:02 UTC
Labels: ongoing work
