### ISSUE TITLE
[request] LevelDB/1.22.0

### ISSUE THREAD

**Issue by osfd** [conan-io/wishlist#256] opened 2020-01-16 09:32 UTC
### Package Details
  * LevelDB/1.22.0
  * Website: https://github.com/google/leveldb/blob/master/doc/index.md
  * Source code: https://github.com/google/leveldb

LevelDB
Now in google i can find only old version. Recipe uses deplecated features from conan. I try create library with this file:

```
from conans import ConanFile, CMake, tools

class LeveldbConan(ConanFile):
    name = "leveldb"
    version = "1.22.0"
    license = "<Put the package license here>"
    author = "<Put your name here> <And your email here>"
    url = "https://github.com/google/leveldb"
    description = "<Description of Leveldb here>"
    topics = ("<Put some tag here>", "<here>", "<and here>")
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}
    default_options = {"shared": False}
    generators = "cmake"

    def source(self):
        self.run("git clone --recurse-submodules https://github.com/google/leveldb.git")
        # This small hack might be useful to guarantee proper /MT /MD linkage
        # in MSVC if the packaged project doesn't have variables to set it
        # properly
        #tools.replace_in_file("hello/CMakeLists.txt", "PROJECT(HelloWorld)",
        #                      '''PROJECT(HelloWorld)
#include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
#conan_basic_setup()''')

    def build(self):
        cmake = CMake(self)
        cmake.configure(source_folder="leveldb")
        cmake.build()

        # Explicit way:
        # self.run('cmake %s/hello %s'
        #          % (self.source_folder, cmake.command_line))
        # self.run("cmake --build . %s" % cmake.build_config)

    def package(self):
        self.copy("*.h", dst="include", src="leveldb")
        self.copy("*.lib", dst="lib", keep_path=False)
        self.copy("*.dll", dst="bin", keep_path=False)
        self.copy("*.so", dst="lib", keep_path=False)
        self.copy("*.dylib", dst="lib", keep_path=False)
        self.copy("*.a", dst="lib", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = ["leveldb"]
```

But it's don't work

**Comment by Croydon** [comment] 2020-01-16 09:36
Duplicate of #25

**Comment by osfd** [comment] 2020-01-20 09:08
I'm fixed it. But i think possible change hardcoded path for copy, to an elegant command.
If it's not interesting, I'm close issue on next week.

**conanfile.py**
```
from conans import ConanFile, CMake, tools


class LeveldbConan(ConanFile):
    name = "leveldb"
    version = "1.22.0"
    license = "<Put the package license here>"
    author = "<Put your name here> <And your email here>"
    url = "https://github.com/google/leveldb"
    description = "<Description of Leveldb here>"
    topics = ("<Put some tag here>", "<here>", "<and here>")
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}
    default_options = {"shared": False}
    generators = "cmake"

    def source(self):
        self.run("git clone --recurse-submodules https://github.com/google/leveldb.git")
        # This small hack might be useful to guarantee proper /MT /MD linkage
        # in MSVC if the packaged project doesn't have variables to set it
        # properly
        #tools.replace_in_file("hello/CMakeLists.txt", "PROJECT(HelloWorld)",
        #                      '''PROJECT(HelloWorld)
#include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
#conan_basic_setup()''')

    def build(self):
        cmake = CMake(self)
        cmake.configure(source_folder="leveldb")
        cmake.build()
        cmake.install()
        # I think it's not good:
        self.run("cp ./CMakeFiles/Export/lib/cmake/leveldb/leveldbTargets.cmake ./cmake")

        # Explicit way:
        # self.run('cmake %s/hello %s'
        #          % (self.source_folder, cmake.command_line))
        # self.run("cmake --build . %s" % cmake.build_config)

    def package(self):
        self.copy("*.h", dst="include", src="leveldb")
        self.copy("*.lib", dst="lib", keep_path=False)
        self.copy("*.dll", dst="bin", keep_path=False)
        self.copy("*.so", dst="lib", keep_path=False)
        self.copy("*.dylib", dst="lib", keep_path=False)
        self.copy("*.a", dst="lib", keep_path=False)


    def package_info(self):
        self.cpp_info.libs = ["leveldb"]

```

**Comment by uilianries** [comment] 2020-01-20 13:45
Hi @osfd !

Could you open a PR to [Conan Center Index](https://github.com/conan-io/conan-center-index) with your recipe. It will be welcome.

Please, follow the [instructions](https://github.com/conan-io/conan-center-index/wiki#adding-packages-to-conancenter) to open a pull request there.

Regards!

**Closed as completed** 2020-05-11 08:50 UTC
